"use strict";

const SERVICE_UUID="4fafc201-1fb5-459e-8fcc-c5c9c331914b";
const CMD_CHAR_UUID="beb5483e-36e1-4688-b7f5-ea07361b26a8";
const TELE_CHAR_UUID="beb5483e-36e1-4688-b7f5-ea07361b26a9";
const OBSTACLE_CM=30, MAX_STEERING=70, EYE_THRESHOLD=.22, EYE_WARN_MS=2000, EYE_ALERT_MS=10000;
const $=(id)=>document.getElementById(id);
const ui={status:$("status"),connectBtn:$("connectBtn"),bleDot:$("bleDot"),bleStatus:$("bleStatus"),gpsStatus:$("gpsStatus"),gsmStatus:$("gsmStatus"),smsStatus:$("smsStatus"),front:$("distFront"),rear:$("distRear"),frontCard:$("frontCard"),rearCard:$("rearCard"),coords:$("coords"),obstacleWarning:$("obstacleWarning"),ecoBtn:$("ecoBtn"),sportBtn:$("sportBtn"),speed:$("speedNum"),rpm:$("rpmNum"),speedGauge:$("speedGauge"),rpmGauge:$("rpmGauge"),drivePanel:$("drivePanel"),cameraPanel:$("cameraPanel"),driverCamera:$("driverCamera"),cameraState:$("cameraState"),eyeState:$("eyeState"),drowsyState:$("drowsyState"),cameraBtn:$("cameraBtn"),drowsyWarning:$("drowsyWarning"),gpsReqBtn:$("gpsReqBtn"),msgInput:$("msgInput"),msgSendBtn:$("msgSendBtn"),msgStatus:$("msgStatus"),moveBtn:$("moveBtn"),stopBtn:$("stopBtn"),gearFwdBtn:$("gearFwdBtn"),gearRevBtn:$("gearRevBtn"),moveLabel:$("moveLabel"),leftBtn:$("leftBtn"),rightBtn:$("rightBtn")};
let bleDevice=null,bleServer=null,cmdChar=null,teleChar=null,currentMode="ECO",currentGear="forward",frontCm=null,rearCm=null,moving=null,steering=0,targetSpeed=0,displaySpeed=0,lastGaugeFrame=0,cameraStream=null,cameraRunning=false,cameraFrameTimer=null,faceMesh=null,eyesClosedSince=0,drowsyPhase="NORMAL",eyeOpenBaseline=.30,smoothedEAR=null;
const setText=(el,text)=>{el.textContent=text};
function setStatus(el,text,state=""){setText(el,text);el.classList.remove("ok","bad");if(state)el.classList.add(state)}
function isDanger(distance){return Number.isFinite(distance)&&distance>0&&distance<=OBSTACLE_CM}
function updateSpeed(speed=0){targetSpeed=speed}
function animateGauges(timestamp){const elapsed=lastGaugeFrame?Math.min((timestamp-lastGaugeFrame)/1000,.1):0;lastGaugeFrame=timestamp;const easing=1-Math.exp(-3.2*elapsed);displaySpeed+=(targetSpeed-displaySpeed)*easing;if(Math.abs(targetSpeed-displaySpeed)<.015)displaySpeed=targetSpeed;setText(ui.speed,Math.round(displaySpeed));setText(ui.rpm,Math.round(displaySpeed*140));const speedProgress=Math.min(1,displaySpeed/25);ui.speedGauge.style.setProperty("--gauge-progress",`${speedProgress*250}deg`);ui.speedGauge.style.setProperty("--needle-angle",`${-135+speedProgress*270}deg`);const rpmProgress=Math.min(1,displaySpeed*140/3500);ui.rpmGauge.style.setProperty("--gauge-progress",`${rpmProgress*250}deg`);ui.rpmGauge.style.setProperty("--needle-angle",`${-135+rpmProgress*270}deg`);requestAnimationFrame(animateGauges)}
function updateMotionUI(){ui.drivePanel.classList.toggle("moving",moving!==null);ui.moveBtn.classList.toggle("active",moving!==null);const speed=moving==="forward"?(currentMode==="SPORT"?25:15):moving==="reverse"?(currentMode==="SPORT"?22:13):0;updateSpeed(speed)}
function updateSteeringUI(){ui.leftBtn.classList.toggle("active",steering<0);ui.rightBtn.classList.toggle("active",steering>0)}
async function sendCmd(command){if(!cmdChar)return false;try{const data=new TextEncoder().encode(command);if(cmdChar.properties.writeWithoutResponse)await cmdChar.writeValueWithoutResponse(data);else if(cmdChar.properties.write)await cmdChar.writeValue(data);else return false;return true}catch(error){console.error("BLE send error:",error);return false}}
async function connectBLE(){if(!navigator.bluetooth){setText(ui.status,"BLE NOT SUPPORTED");setStatus(ui.bleStatus,"UNSUPPORTED","bad");return}try{setText(ui.status,"REQUESTING DEVICE...");bleDevice=await navigator.bluetooth.requestDevice({filters:[{services:[SERVICE_UUID]}]});bleDevice.addEventListener("gattserverdisconnected",onDisconnected,{once:true});setText(ui.status,"CONNECTING...");bleServer=await bleDevice.gatt.connect();const service=await bleServer.getPrimaryService(SERVICE_UUID);cmdChar=await service.getCharacteristic(CMD_CHAR_UUID);teleChar=await service.getCharacteristic(TELE_CHAR_UUID);await teleChar.startNotifications();teleChar.addEventListener("characteristicvaluechanged",onTelemetry);setText(ui.status,"CONNECTED");setStatus(ui.bleStatus,"CONNECTED","ok");ui.bleDot.className="status-dot ok";ui.connectBtn.textContent="CONNECTED";await sendCmd(`MODE:${currentMode}`)}catch(error){console.error("BLE connection error:",error);setText(ui.status,"CONNECTION FAILED");setStatus(ui.bleStatus,"DISCONNECTED","bad");ui.bleDot.className="status-dot bad";cmdChar=null;teleChar=null;bleServer=null}}
function onDisconnected(){cmdChar=null;teleChar=null;bleServer=null;stopMotion(false);setText(ui.status,"DISCONNECTED");setStatus(ui.bleStatus,"DISCONNECTED","bad");ui.bleDot.className="status-dot bad";ui.connectBtn.textContent="CONNECT TO CAR"}
function showObstacle(direction){setText(ui.obstacleWarning,`⚠ ${direction.toUpperCase()} OBSTACLE DETECTED — VEHICLE STOPPED`);ui.obstacleWarning.classList.add("active")}
function clearObstacle(){if(!isDanger(frontCm)&&!isDanger(rearCm))ui.obstacleWarning.classList.remove("active")}
function stopMotion(sendStop=true){const hadSteering=steering!==0;moving=null;steering=0;updateMotionUI();updateSteeringUI();if(sendStop){if(hadSteering)sendCmd("L:0");sendCmd("S")}}
function startMotion(direction){if(drowsyPhase!=="NORMAL"){stopMotion(true);return}if((direction==="forward"&&isDanger(frontCm))||(direction==="reverse"&&isDanger(rearCm))){showObstacle(direction);stopMotion(true);return}ui.obstacleWarning.classList.remove("active");moving=direction;updateMotionUI();sendCmd(direction==="forward"?"F":"B")}
function releaseMotion(){if(moving===null)return;moving=null;updateMotionUI();sendCmd("S")}
function setGear(gear){if(moving!==null)stopMotion(true);currentGear=gear;ui.gearFwdBtn.classList.toggle("active",gear==="forward");ui.gearRevBtn.classList.toggle("active",gear==="reverse");ui.gearFwdBtn.setAttribute("aria-pressed",String(gear==="forward"));ui.gearRevBtn.setAttribute("aria-pressed",String(gear==="reverse"));setText(ui.moveLabel,gear==="forward"?"HOLD TO MOVE":"HOLD TO REVERSE")}
function releaseSteering(value){if(steering!==value)return;steering=0;updateSteeringUI();sendCmd("L:0")}
function setSteering(value){if(drowsyPhase!=="NORMAL"&&value!==0)return;steering=Math.max(-MAX_STEERING,Math.min(MAX_STEERING,value));updateSteeringUI();sendCmd(`L:${steering}`)}
function checkObstacle(){if((moving==="forward"&&isDanger(frontCm))||(moving==="reverse"&&isDanger(rearCm))){showObstacle(moving);stopMotion(true);return}clearObstacle()}
function onTelemetry(event){const value=new TextDecoder().decode(event.target.value);const frontMatch=value.match(/F:(-?\d+)/),rearMatch=value.match(/R:(-?\d+)/),gpsMatch=value.match(/GPS:(\d)/),latMatch=value.match(/LAT:([-0-9.]+)/),lonMatch=value.match(/LON:([-0-9.]+)/),gsmMatch=value.match(/GSM:(\d)/),smsMatch=value.match(/SMS:([^,\s]+)/);if(frontMatch){frontCm=Number(frontMatch[1]);setText(ui.front,frontCm);ui.frontCard.classList.toggle("danger",isDanger(frontCm))}if(rearMatch){rearCm=Number(rearMatch[1]);setText(ui.rear,rearCm);ui.rearCard.classList.toggle("danger",isDanger(rearCm))}if(gpsMatch)setStatus(ui.gpsStatus,gpsMatch[1]==="1"?"FIX ACQUIRED":"NO FIX",gpsMatch[1]==="1"?"ok":"bad");if(latMatch&&lonMatch)setText(ui.coords,`${latMatch[1]}, ${lonMatch[1]}`);if(gsmMatch)setStatus(ui.gsmStatus,gsmMatch[1]==="1"?"CONNECTED":"DISCONNECTED",gsmMatch[1]==="1"?"ok":"bad");if(smsMatch)setStatus(ui.smsStatus,smsMatch[1],smsMatch[1]==="1"?"ok":"");checkObstacle()}
function setMode(mode){currentMode=mode;ui.ecoBtn.classList.toggle("active",mode==="ECO");ui.sportBtn.classList.toggle("active",mode==="SPORT");ui.sportBtn.classList.toggle("sport",mode==="SPORT");sendCmd(`MODE:${mode}`);updateMotionUI()}
function setDrowsyUI(){ui.drowsyState.className="driver-drowsy";setText(ui.drowsyState,"SLEEPY DRIVER");ui.drowsyWarning.classList.add("active")}
function clearDrowsyUI(){ui.drowsyState.className="driver-normal";setText(ui.drowsyState,"DRIVER NORMAL");ui.drowsyWarning.classList.remove("active")}
function processEyeState(eyesClosed){if(!eyesClosed){setText(ui.eyeState,"EYES: OPEN");eyesClosedSince=0;if(drowsyPhase!=="NORMAL"){drowsyPhase="NORMAL";clearDrowsyUI();sendCmd("EYE:CLEAR")}return}setText(ui.eyeState,"EYES: CLOSED");if(!eyesClosedSince)eyesClosedSince=Date.now();const elapsed=Date.now()-eyesClosedSince,next=elapsed>=EYE_ALERT_MS?"ALERT":elapsed>=EYE_WARN_MS?"WARN":"NORMAL";if(next!=="NORMAL"&&next!==drowsyPhase){drowsyPhase=next;setDrowsyUI();stopMotion(true);sendCmd(next==="ALERT"?"EYE:ALERT":"EYE:WARN")}}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function calculateEAR(landmarks,points){const[p1,p2,p3,p4,p5,p6]=points.map(point=>landmarks[point]);const horizontal=distance(p1,p4);return horizontal?(distance(p2,p6)+distance(p3,p5))/(2*horizontal):1}
function handleFaceResults(results){if(!results.multiFaceLandmarks?.length){setText(ui.eyeState,"FACE NOT DETECTED");smoothedEAR=null;return}const points=results.multiFaceLandmarks[0],left=calculateEAR(points,[33,160,158,133,153,144]),right=calculateEAR(points,[362,385,387,263,373,380]),ear=(left+right)/2;smoothedEAR=smoothedEAR===null?ear:smoothedEAR*.65+ear*.35;const threshold=Math.min(EYE_THRESHOLD,eyeOpenBaseline*.70);if(smoothedEAR>threshold)eyeOpenBaseline=eyeOpenBaseline*.98+smoothedEAR*.02;processEyeState(smoothedEAR<threshold)}
function setupFaceMesh(){if(typeof FaceMesh==="undefined"){setText(ui.cameraState,"FACE MESH ERROR");return false}faceMesh=new FaceMesh({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`});faceMesh.setOptions({maxNumFaces:1,refineLandmarks:true,minDetectionConfidence:.5,minTrackingConfidence:.5});faceMesh.onResults(handleFaceResults);return true}
async function runFaceDetection(){if(!cameraRunning||!faceMesh)return;try{if(ui.driverCamera.readyState>=HTMLMediaElement.HAVE_CURRENT_DATA)await faceMesh.send({image:ui.driverCamera})}catch(error){console.error("Face detection error:",error)}if(cameraRunning)cameraFrameTimer=setTimeout(runFaceDetection,66)}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){setText(ui.cameraState,"CAMERA NOT SUPPORTED");return}try{setText(ui.cameraState,"STARTING CAMERA...");cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});ui.driverCamera.srcObject=cameraStream;await ui.driverCamera.play();if(!setupFaceMesh()){stopCamera();return}cameraRunning=true;setText(ui.cameraState,"CAMERA ACTIVE");ui.cameraBtn.textContent="STOP CAMERA";runFaceDetection()}catch(error){console.error("Camera error:",error);setText(ui.cameraState,"CAMERA ERROR")}}
function stopCamera(){cameraRunning=false;if(cameraFrameTimer){clearTimeout(cameraFrameTimer);cameraFrameTimer=null}if(cameraStream)cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;ui.driverCamera.srcObject=null;faceMesh=null;eyesClosedSince=0;eyeOpenBaseline=.30;smoothedEAR=null;if(drowsyPhase!=="NORMAL")sendCmd("EYE:CLEAR");drowsyPhase="NORMAL";clearDrowsyUI();setText(ui.eyeState,"EYES: --");setText(ui.cameraState,"CAMERA OFF");ui.cameraBtn.textContent="START CAMERA"}
function bindHold(button,onStart,onEnd){button.addEventListener("pointerdown",event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);onStart()});["pointerup","pointercancel","lostpointercapture"].forEach(type=>button.addEventListener(type,onEnd))}
ui.connectBtn.addEventListener("click",connectBLE);ui.gearFwdBtn.addEventListener("click",()=>setGear("forward"));ui.gearRevBtn.addEventListener("click",()=>setGear("reverse"));ui.stopBtn.addEventListener("pointerdown",event=>{event.preventDefault();stopMotion(true)});ui.stopBtn.addEventListener("click",event=>{if(event.detail===0)stopMotion(true)});ui.ecoBtn.addEventListener("click",()=>setMode("ECO"));ui.sportBtn.addEventListener("click",()=>setMode("SPORT"));ui.gpsReqBtn.addEventListener("click",()=>sendCmd("GPS?"));ui.msgSendBtn.addEventListener("click",async()=>{const message=ui.msgInput.value.trim();if(!message){setText(ui.msgStatus,"ENTER A MESSAGE");return}setText(ui.msgStatus,"SENDING...");if(await sendCmd(`MSG:${message}`)){ui.msgInput.value="";setText(ui.msgStatus,"MESSAGE SENT")}else setText(ui.msgStatus,"CAR NOT CONNECTED")});ui.cameraBtn.addEventListener("click",()=>cameraRunning?stopCamera():startCamera());bindHold(ui.moveBtn,()=>startMotion(currentGear),releaseMotion);bindHold(ui.leftBtn,()=>setSteering(-MAX_STEERING),()=>releaseSteering(-MAX_STEERING));bindHold(ui.rightBtn,()=>setSteering(MAX_STEERING),()=>releaseSteering(MAX_STEERING));requestAnimationFrame(animateGauges);window.addEventListener("blur",()=>stopMotion(true));document.addEventListener("visibilitychange",()=>{if(document.hidden)stopMotion(true)});updateSpeed(0);
