"use strict";

const SERVICE_UUID="4fafc201-1fb5-459e-8fcc-c5c9c331914b";
const CMD_CHAR_UUID="beb5483e-36e1-4688-b7f5-ea07361b26a8";
const TELE_CHAR_UUID="beb5483e-36e1-4688-b7f5-ea07361b26a9";
const OBSTACLE_CM=30, PARKING_STOP_CM=1, MAX_STEERING=70, EYE_THRESHOLD=.22, EYE_WARN_MS=2000, EYE_ALERT_MS=10000;
const $=(id)=>document.getElementById(id);
const ui={status:$("status"),connectBtn:$("connectBtn"),bleDot:$("bleDot"),bleStatus:$("bleStatus"),gpsStatus:$("gpsStatus"),gsmStatus:$("gsmStatus"),smsStatus:$("smsStatus"),front:$("distFront"),rear:$("distRear"),frontCard:$("frontCard"),rearCard:$("rearCard"),coords:$("coords"),obstacleWarning:$("obstacleWarning"),driveDirection:$("driveDirection"),obstacleReadout:$("obstacleReadout"),ecoBtn:$("ecoBtn"),sportBtn:$("sportBtn"),speed:$("speedNum"),rpm:$("rpmNum"),speedGauge:$("speedGauge"),rpmGauge:$("rpmGauge"),drivePanel:$("drivePanel"),cameraPanel:$("cameraPanel"),driverCamera:$("driverCamera"),cameraState:$("cameraState"),eyeState:$("eyeState"),drowsyState:$("drowsyState"),cameraBtn:$("cameraBtn"),drowsyWarning:$("drowsyWarning"),gpsReqBtn:$("gpsReqBtn"),msgInput:$("msgInput"),msgSendBtn:$("msgSendBtn"),msgStatus:$("msgStatus"),moveBtn:$("moveBtn"),stopBtn:$("stopBtn"),gearFwdBtn:$("gearFwdBtn"),gearRevBtn:$("gearRevBtn"),moveLabel:$("moveLabel"),leftBtn:$("leftBtn"),rightBtn:$("rightBtn")};
ui.parkingBtn=$("parkingBtn");
let bleDevice=null,bleServer=null,cmdChar=null,teleChar=null,currentMode="ECO",parkingMode=false,currentGear="forward",frontCm=null,rearCm=null,gpsFix=null,latitude=null,longitude=null,gsmConnected=null,smsState="READY",moving=null,steering=0,targetSpeed=0,displaySpeed=0,lastGaugeFrame=0,cameraStream=null,cameraRunning=false,cameraFrameTimer=null,faceMesh=null,eyesClosedSince=0,drowsyPhase="NORMAL",eyeOpenBaseline=.30,smoothedEAR=null;
const eventHistory=[];let activePanel=null;
const setText=(el,text)=>{el.textContent=text};
function setStatus(el,text,state=""){setText(el,text);el.classList.remove("ok","bad");if(state)el.classList.add(state)}
function isDanger(distance){return Number.isFinite(distance)&&distance>0&&distance<=OBSTACLE_CM}
function isMotionBlocked(direction){const distance=direction==="forward"?frontCm:rearCm;return Number.isFinite(distance)&&(parkingMode?distance>=0&&distance<=PARKING_STOP_CM:isDanger(distance))}
function updateDriveReadout(){if(!ui.driveDirection||!ui.obstacleReadout)return;setText(ui.driveDirection,moving==="forward"?"MOVING FORWARD":moving==="reverse"?"MOVING REVERSE":"STOPPED");ui.driveDirection.className=moving?"readout-active":"";const frontBlocked=isDanger(frontCm),rearBlocked=isDanger(rearCm),known=frontCm!==null||rearCm!==null;setText(ui.obstacleReadout,!known?"WAITING FOR SENSOR":frontBlocked&&rearBlocked?"FRONT + REAR DETECTED":frontBlocked?"FRONT DETECTED":rearBlocked?"REAR DETECTED":"CLEAR");ui.obstacleReadout.className=frontBlocked||rearBlocked?"readout-danger":known?"readout-clear":"readout-neutral"}
function updateConnectionScreen(){const states=[["screenBleStatus",cmdChar?"CONNECTED":"DISCONNECTED",cmdChar?"ok":"bad"],["screenGpsStatus",gpsFix===null?"NO FIX":gpsFix?"FIX ACQUIRED":"NO FIX",gpsFix===null?"neutral":gpsFix?"ok":"bad"],["screenGsmStatus",gsmConnected===null?"UNKNOWN":gsmConnected?"CONNECTED":"DISCONNECTED",gsmConnected===null?"neutral":gsmConnected?"ok":"bad"],["screenSmsStatus",smsState,smsState==="SENT"?"ok":smsState==="FAILED"?"bad":"neutral"]];for(const[id,value,state]of states){const element=$(id);if(element){setText(element,value);element.className=`screen-${state}`}}}
function addEventLog(message){eventHistory.unshift({time:new Date().toLocaleTimeString(),message});if(eventHistory.length>50)eventHistory.length=50;refreshActivePanel()}
function valueState(value,yes,no,unknown="UNAVAILABLE"){return value===null?unknown:value?yes:no}
function openMenu(){const d=$("sideDrawer");$("drawerBackdrop").hidden=false;d.classList.add("open");d.inert=false;d.setAttribute("aria-hidden","false");$("menuOpenBtn").setAttribute("aria-expanded","true");$("menuCloseBtn").focus()}
function closeMenu(){const d=$("sideDrawer");d.classList.remove("open");d.inert=true;d.setAttribute("aria-hidden","true");$("drawerBackdrop").hidden=true;$("menuOpenBtn").setAttribute("aria-expanded","false")}
function openPanel(name){if(name==="dashboard"){closePanel();closeMenu();return}closeMenu();const title=$("panelTitle"),content=$("panelContent");const renderers={telemetry:renderTelemetryPanel,safety:renderSafetyPanel,events:renderEventPanel,ble:renderBlePanel,gps:renderGpsPanel,driver:renderDriverPanel,project:renderProjectPanel};if(!renderers[name])return;activePanel=name;title.textContent={telemetry:"LIVE TELEMETRY",safety:"SAFETY STATUS",events:"EVENT LOG",ble:"BLE / CONNECTION",gps:"GPS INFORMATION",driver:"DRIVER MONITOR",project:"PROJECT INFO"}[name];content.replaceChildren();renderers[name](content);$("panelOverlay").hidden=false;$("panelCloseBtn").focus()}
function closePanel(){$("panelOverlay").hidden=true;activePanel=null}
function openPanelContent(name){const content=$("panelContent"),renderers={telemetry:renderTelemetryPanel,safety:renderSafetyPanel,events:renderEventPanel,ble:renderBlePanel,gps:renderGpsPanel,driver:renderDriverPanel,project:renderProjectPanel};if(renderers[name])renderers[name](content)}
function refreshActivePanel(){if(activePanel)openPanelContent(activePanel)}
function row(label,value,state="neutral"){return `<div class="data-row"><span>${label}</span><strong class="${state}">${value}</strong></div>`}
function renderTelemetryPanel(c){c.innerHTML=`<div class="data-grid">${row("FRONT DISTANCE",frontCm===null?"-- cm":`${frontCm} cm`,isDanger(frontCm)?"bad":"ok")}${row("REAR DISTANCE",rearCm===null?"-- cm":`${rearCm} cm`,isDanger(rearCm)?"bad":"ok")}${row("GPS STATUS",valueState(gpsFix,"FIX","NO FIX"),gpsFix===null?"neutral":gpsFix?"ok":"bad")}${row("LATITUDE",latitude??"--")}${row("LONGITUDE",longitude??"--")}${row("GSM STATUS",valueState(gsmConnected,"CONNECTED","DISCONNECTED"),gsmConnected===null?"neutral":gsmConnected?"ok":"bad")}${row("SMS STATUS",smsState)}${row("BLE STATUS",cmdChar?"CONNECTED":"DISCONNECTED",cmdChar?"ok":"bad")}${row("DRIVER STATUS",drowsyPhase==="NORMAL"?"NORMAL":drowsyPhase,drowsyPhase==="NORMAL"?"ok":"bad")}${row("CURRENT MODE",parkingMode?`${currentMode} / PARKING`:currentMode)}${row("CURRENT GEAR",currentGear.toUpperCase())}${row("SPEED","WEB CONTROL")}${row("RPM","WEB CONTROL")}</div>`}
function renderSafetyPanel(c){const items=[["BLE",!!cmdChar,"CONNECTED","DISCONNECTED"],["CAMERA",cameraRunning,"ACTIVE","OFF"],["DRIVER",drowsyPhase==="NORMAL",drowsyPhase==="NORMAL"?"NORMAL":"SLEEPY","SLEEPY"],["FRONT",frontCm===null?null:!isDanger(frontCm),"CLEAR","BLOCKED"],["REAR",rearCm===null?null:!isDanger(rearCm),"CLEAR","BLOCKED"],["GPS",gpsFix,"FIX","NO FIX"],["GSM",gsmConnected,"CONNECTED","DISCONNECTED"]];c.innerHTML='<h3>SYSTEM SAFETY</h3><div class="data-grid">'+items.map(([n,v,y,no])=>row(n,valueState(v,y,no),v===null?"neutral":v?"ok":"bad")).join("")+row("VEHICLE",moving!==null?"READY":"STOPPED",drowsyPhase!=="NORMAL"?"bad":"ok")+'</div>'}
function renderEventLog(c){c.innerHTML='<div class="event-actions"><button type="button" id="clearLogBtn">CLEAR LOG</button></div><div id="eventList" class="event-list"></div>';$("clearLogBtn").addEventListener("click",()=>{eventHistory.length=0;renderEventLog($("panelContent"))});const list=$("eventList");list.replaceChildren(...eventHistory.map(item=>{const e=document.createElement("article");e.className="event-entry";const t=document.createElement("time");t.textContent=item.time;const m=document.createElement("strong");m.textContent=item.message;e.append(t,m);return e}))}
function renderBlePanel(c){c.innerHTML=`<div class="data-grid">${row("BLE STATUS",bleStatusLabel(),cmdChar?"ok":bleDevice?"bad":"neutral")}${row("DEVICE",bleDevice?.name||"NOT SELECTED")}${row("SERVICE",SERVICE_UUID)}${row("COMMAND CHARACTERISTIC",CMD_CHAR_UUID)}${row("TELEMETRY CHARACTERISTIC",TELE_CHAR_UUID)}</div><button id="reconnectBtn" type="button" class="panel-action">RECONNECT</button>`;$("reconnectBtn").addEventListener("click",connectBLE)}
function bleStatusLabel(){return !navigator.bluetooth?"BLE NOT SUPPORTED":cmdChar?"CONNECTED":bleDevice?"CONNECTION FAILED":"DISCONNECTED"}
function renderGpsPanel(c){c.innerHTML=`<div class="data-grid">${row("GPS STATUS",valueState(gpsFix,"FIX ACQUIRED","NO FIX"),gpsFix===null?"neutral":gpsFix?"ok":"bad")}${row("LATITUDE",latitude??"--")}${row("LONGITUDE",longitude??"--")}${row("LAST TELEMETRY VALUE",latitude&&longitude?`${latitude}, ${longitude}`:"--")}</div><button id="panelGpsBtn" type="button" class="panel-action">REQUEST GPS</button>`;$("panelGpsBtn").addEventListener("click",()=>sendCmd("GPS?"))}
function renderDriverPanel(c){c.innerHTML=`<div class="data-grid">${row("CAMERA",cameraRunning?"ACTIVE":"OFF",cameraRunning?"ok":"neutral")}${row("EYE STATUS",ui.eyeState.textContent)}${row("DRIVER STATUS",drowsyPhase==="NORMAL"?"NORMAL":drowsyPhase,drowsyPhase==="NORMAL"?"ok":"bad")}${row("DROWSINESS PHASE",drowsyPhase)}${row("EAR VALUE",smoothedEAR===null?"UNAVAILABLE":smoothedEAR.toFixed(3))}${row("DETECTION STATE",faceMesh?"FACE MESH READY":"WAITING FOR CAMERA")}</div><p class="panel-note">NORMAL: eyes open. WARNING: eyes closed for 2 seconds. ALERT: eyes closed for 10 seconds.</p>`}
function renderProjectPanel(c){c.innerHTML='<h3>RC CAR CONTROL &amp; DRIVER SAFETY SYSTEM</h3><p>A browser based control dashboard for an ESP32 powered RC car. It brings driving controls, sensor status, driver monitoring, and location and messaging tools into one interface.</p><div class="project-section"><h4>CONTROL &amp; DRIVE</h4><p>Connects to the car over Web Bluetooth. Hold to move forward or reverse, hold the steering controls to steer, and release to send a stop or center steering command. ECO and SPORT modes are available, with the selected gear and mode shown in the dashboard.</p></div><div class="project-section"><h4>SAFETY MONITORING</h4><p>Front and rear distance telemetry uses a 30 cm movement stop in normal driving. Optional PARKING mode displays a low-clearance warning and lowers the browser-side stop threshold to 1 cm. MediaPipe Face Mesh estimates eye closure using EAR; the existing logic sends warning and alert signals after 2 and 10 seconds and stops vehicle movement when drowsiness is detected.</p></div><div class="project-section"><h4>TELEMETRY &amp; CONNECTIVITY</h4><p>The web page reads front/rear distance, GPS fix and coordinates, GSM state, and SMS status from the BLE telemetry characteristic. It can request GPS data and send SMS commands. Speed and RPM gauges reflect web control state; they are not vehicle speed or RPM telemetry.</p><p class="project-code">Telemetry fields: <code>F:</code> front distance · <code>R:</code> rear distance · <code>GPS:</code> fix · <code>LAT:</code> latitude · <code>LON:</code> longitude · <code>GSM:</code> modem state · <code>SMS:</code> message state</p></div><div class="project-section"><h4>TECHNOLOGY</h4><p>ESP32 · ESP32-C3 where applicable · Web Bluetooth · MediaPipe Face Mesh · HTML · CSS · JavaScript</p></div><p class="panel-note">The ESP32 remains responsible for the final physical safety layer.</p>'}
function renderEventPanel(c){renderEventLog(c)}
function updateSpeed(speed=0){targetSpeed=speed}
function animateGauges(timestamp){const elapsed=lastGaugeFrame?Math.min((timestamp-lastGaugeFrame)/1000,.1):0;lastGaugeFrame=timestamp;const easing=1-Math.exp(-3.2*elapsed);displaySpeed+=(targetSpeed-displaySpeed)*easing;if(Math.abs(targetSpeed-displaySpeed)<.015)displaySpeed=targetSpeed;setText(ui.speed,Math.round(displaySpeed));setText(ui.rpm,Math.round(displaySpeed*140));const speedProgress=Math.min(1,displaySpeed/25);ui.speedGauge.style.setProperty("--gauge-progress",`${speedProgress*250}deg`);ui.speedGauge.style.setProperty("--needle-angle",`${-135+speedProgress*270}deg`);const rpmProgress=Math.min(1,displaySpeed*140/3500);ui.rpmGauge.style.setProperty("--gauge-progress",`${rpmProgress*250}deg`);ui.rpmGauge.style.setProperty("--needle-angle",`${-135+rpmProgress*270}deg`);requestAnimationFrame(animateGauges)}
function updateMotionUI(){ui.drivePanel.classList.toggle("moving",moving!==null);ui.moveBtn.classList.toggle("active",moving!==null);const speed=moving==="forward"?(currentMode==="SPORT"?25:15):moving==="reverse"?(currentMode==="SPORT"?22:13):0;updateSpeed(speed);updateDriveReadout();refreshActivePanel()}
function updateSteeringUI(){ui.leftBtn.classList.toggle("active",steering<0);ui.rightBtn.classList.toggle("active",steering>0)}
async function sendCmd(command){if(!cmdChar)return false;try{const data=new TextEncoder().encode(command);if(cmdChar.properties.writeWithoutResponse)await cmdChar.writeValueWithoutResponse(data);else if(cmdChar.properties.write)await cmdChar.writeValue(data);else return false;return true}catch(error){console.error("BLE send error:",error);return false}}
async function connectBLE(){if(!navigator.bluetooth){setText(ui.status,"BLE NOT SUPPORTED");setStatus(ui.bleStatus,"UNSUPPORTED","bad");updateConnectionScreen();addEventLog("BLE NOT SUPPORTED");return}try{setText(ui.status,"REQUESTING DEVICE...");bleDevice=await navigator.bluetooth.requestDevice({filters:[{services:[SERVICE_UUID]}]});bleDevice.addEventListener("gattserverdisconnected",onDisconnected,{once:true});setText(ui.status,"CONNECTING...");bleServer=await bleDevice.gatt.connect();const service=await bleServer.getPrimaryService(SERVICE_UUID);cmdChar=await service.getCharacteristic(CMD_CHAR_UUID);teleChar=await service.getCharacteristic(TELE_CHAR_UUID);await teleChar.startNotifications();teleChar.addEventListener("characteristicvaluechanged",onTelemetry);setText(ui.status,"CONNECTED");setStatus(ui.bleStatus,"CONNECTED","ok");ui.bleDot.className="status-dot ok";ui.connectBtn.textContent="CONNECTED";updateConnectionScreen();addEventLog("BLE CONNECTED");await sendCmd(`MODE:${currentMode}`)}catch(error){console.error("BLE connection error:",error);setText(ui.status,"CONNECTION FAILED");setStatus(ui.bleStatus,"DISCONNECTED","bad");ui.bleDot.className="status-dot bad";cmdChar=null;teleChar=null;bleServer=null;updateConnectionScreen();addEventLog("BLE CONNECTION FAILED")}}
function onDisconnected(){cmdChar=null;teleChar=null;bleServer=null;stopMotion(false);sendCmd("S");setText(ui.status,"DISCONNECTED");setStatus(ui.bleStatus,"DISCONNECTED","bad");ui.bleDot.className="status-dot bad";ui.connectBtn.textContent="CONNECT TO CAR";updateConnectionScreen();addEventLog("BLE DISCONNECTED")}
function showObstacle(direction){setText(ui.obstacleWarning,`⚠ ${direction.toUpperCase()} OBSTACLE DETECTED — VEHICLE STOPPED`);ui.obstacleWarning.classList.remove("parking-caution");ui.obstacleWarning.classList.add("active");const event=`${direction.toUpperCase()} OBSTACLE DETECTED`;if(eventHistory[0]?.message!==event)addEventLog(event)}
function clearObstacle(){if(parkingMode){if([frontCm,rearCm].some(distance=>Number.isFinite(distance)&&distance>=0&&distance<=PARKING_STOP_CM)){setText(ui.obstacleWarning,"⚠ PARKING LIMIT REACHED — VEHICLE STOPPED");ui.obstacleWarning.classList.remove("parking-caution");ui.obstacleWarning.classList.add("active");return}const lowClearance=[frontCm,rearCm].some(distance=>Number.isFinite(distance)&&distance>0&&distance<=OBSTACLE_CM);if(lowClearance){setText(ui.obstacleWarning,"⚠ PARKING MODE — LOW CLEARANCE, STOP AT 1 CM");ui.obstacleWarning.classList.add("active","parking-caution");return}}if(ui.obstacleWarning.classList.contains("parking-caution")){ui.obstacleWarning.classList.remove("parking-caution");if(isDanger(frontCm)||isDanger(rearCm)){setText(ui.obstacleWarning,"⚠ OBSTACLE DETECTED — NORMAL MODE STOP LIMIT: 30 CM");return}}if(!isDanger(frontCm)&&!isDanger(rearCm))ui.obstacleWarning.classList.remove("active","parking-caution")}
function stopMotion(sendStop=true){const wasMoving=moving!==null;const hadSteering=steering!==0;moving=null;steering=0;updateMotionUI();updateSteeringUI();if(wasMoving)addEventLog("VEHICLE STOPPED");if(sendStop){if(hadSteering)sendCmd("L:0");sendCmd("S")}}
function startMotion(direction){if(drowsyPhase!=="NORMAL"){stopMotion(true);return}if(isMotionBlocked(direction)){showObstacle(direction);stopMotion(true);return}moving=direction;updateMotionUI();clearObstacle();sendCmd(direction==="forward"?"F":"B")}
function releaseMotion(){if(moving===null)return;moving=null;updateMotionUI();sendCmd("S")}
function setGear(gear){if(moving!==null)stopMotion(true);currentGear=gear;addEventLog(`${gear.toUpperCase()} SELECTED`);ui.gearFwdBtn.classList.toggle("active",gear==="forward");ui.gearRevBtn.classList.toggle("active",gear==="reverse");ui.gearFwdBtn.setAttribute("aria-pressed",String(gear==="forward"));ui.gearRevBtn.setAttribute("aria-pressed",String(gear==="reverse"));setText(ui.moveLabel,gear==="forward"?"HOLD TO MOVE":"HOLD TO REVERSE")}
function releaseSteering(value){if(steering!==value)return;steering=0;updateSteeringUI();sendCmd("L:0")}
function setSteering(value){if(drowsyPhase!=="NORMAL"&&value!==0)return;steering=Math.max(-MAX_STEERING,Math.min(MAX_STEERING,value));updateSteeringUI();sendCmd(`L:${steering}`)}
function checkObstacle(){if(moving&&isMotionBlocked(moving)){showObstacle(moving);stopMotion(true);return}clearObstacle()}
function onTelemetry(event){const value=new TextDecoder().decode(event.target.value);const frontMatch=value.match(/F:(-?\d+)/),rearMatch=value.match(/R:(-?\d+)/),gpsMatch=value.match(/GPS:(\d)/),latMatch=value.match(/LAT:([-0-9.]+)/),lonMatch=value.match(/LON:([-0-9.]+)/),gsmMatch=value.match(/GSM:(\d)/),smsMatch=value.match(/SMS:([^,\s]+)/);if(frontMatch){frontCm=Number(frontMatch[1]);setText(ui.front,frontCm);ui.frontCard.classList.toggle("danger",isDanger(frontCm))}if(rearMatch){rearCm=Number(rearMatch[1]);setText(ui.rear,rearCm);ui.rearCard.classList.toggle("danger",isDanger(rearCm))}if(gpsMatch){const next=gpsMatch[1]==="1";if(gpsFix!==next)addEventLog(next?"GPS FIX ACQUIRED":"GPS FIX LOST");gpsFix=next;setStatus(ui.gpsStatus,next?"FIX ACQUIRED":"NO FIX",next?"ok":"bad")}if(latMatch&&lonMatch){latitude=latMatch[1];longitude=lonMatch[1];setText(ui.coords,`${latitude}, ${longitude}`)}if(gsmMatch){const next=gsmMatch[1]==="1";if(gsmConnected!==next)addEventLog(next?"GSM CONNECTED":"GSM DISCONNECTED");gsmConnected=next;setStatus(ui.gsmStatus,next?"CONNECTED":"DISCONNECTED",next?"ok":"bad")}if(smsMatch){smsState=smsMatch[1];setStatus(ui.smsStatus,smsState,smsState==="1"?"ok":"")}checkObstacle();updateDriveReadout();updateConnectionScreen();if(activePanel)openPanelContent(activePanel)}
function setMode(mode){if(parkingMode)setParkingMode(false);if(currentMode!==mode)addEventLog(`${mode} MODE SELECTED`);currentMode=mode;ui.ecoBtn.classList.toggle("active",mode==="ECO");ui.sportBtn.classList.toggle("active",mode==="SPORT");ui.sportBtn.classList.toggle("sport",mode==="SPORT");sendCmd(`MODE:${mode}`);updateMotionUI()}
function setParkingMode(enabled){if(parkingMode===enabled)return;parkingMode=enabled;ui.parkingBtn.classList.toggle("active",enabled);ui.parkingBtn.setAttribute("aria-pressed",String(enabled));ui.drivePanel.classList.toggle("parking-mode",enabled);addEventLog(enabled?"PARKING MODE SELECTED":"PARKING MODE OFF");if(!enabled&&moving&&isMotionBlocked(moving)){showObstacle(moving);stopMotion(true)}clearObstacle();updateMotionUI()}
function setDrowsyUI(){ui.drowsyState.className="driver-drowsy";setText(ui.drowsyState,"SLEEPY DRIVER");ui.drowsyWarning.classList.add("active")}
function clearDrowsyUI(){ui.drowsyState.className="driver-normal";setText(ui.drowsyState,"DRIVER NORMAL");ui.drowsyWarning.classList.remove("active")}
function processEyeState(eyesClosed){if(!eyesClosed){setText(ui.eyeState,"EYES: OPEN");eyesClosedSince=0;if(drowsyPhase!=="NORMAL"){drowsyPhase="NORMAL";addEventLog("DRIVER NORMAL");clearDrowsyUI();sendCmd("EYE:CLEAR")}return}setText(ui.eyeState,"EYES: CLOSED");if(!eyesClosedSince)eyesClosedSince=Date.now();const elapsed=Date.now()-eyesClosedSince,next=elapsed>=EYE_ALERT_MS?"ALERT":elapsed>=EYE_WARN_MS?"WARN":"NORMAL";if(next!=="NORMAL"&&next!==drowsyPhase){drowsyPhase=next;addEventLog(next==="ALERT"?"DRIVER ALERT":"DRIVER WARNING");setDrowsyUI();stopMotion(true);sendCmd(next==="ALERT"?"EYE:ALERT":"EYE:WARN")}}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function calculateEAR(landmarks,points){const[p1,p2,p3,p4,p5,p6]=points.map(point=>landmarks[point]);const horizontal=distance(p1,p4);return horizontal?(distance(p2,p6)+distance(p3,p5))/(2*horizontal):1}
function handleFaceResults(results){if(!results.multiFaceLandmarks?.length){setText(ui.eyeState,"FACE NOT DETECTED");smoothedEAR=null;return}const points=results.multiFaceLandmarks[0],left=calculateEAR(points,[33,160,158,133,153,144]),right=calculateEAR(points,[362,385,387,263,373,380]),ear=(left+right)/2;smoothedEAR=smoothedEAR===null?ear:smoothedEAR*.65+ear*.35;const threshold=Math.min(EYE_THRESHOLD,eyeOpenBaseline*.70);if(smoothedEAR>threshold)eyeOpenBaseline=eyeOpenBaseline*.98+smoothedEAR*.02;processEyeState(smoothedEAR<threshold)}
function setupFaceMesh(){if(typeof FaceMesh==="undefined"){setText(ui.cameraState,"FACE MESH ERROR");return false}faceMesh=new FaceMesh({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`});faceMesh.setOptions({maxNumFaces:1,refineLandmarks:true,minDetectionConfidence:.5,minTrackingConfidence:.5});faceMesh.onResults(handleFaceResults);return true}
async function runFaceDetection(){if(!cameraRunning||!faceMesh)return;try{if(ui.driverCamera.readyState>=HTMLMediaElement.HAVE_CURRENT_DATA)await faceMesh.send({image:ui.driverCamera})}catch(error){console.error("Face detection error:",error)}if(cameraRunning)cameraFrameTimer=setTimeout(runFaceDetection,66)}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){setText(ui.cameraState,"CAMERA NOT SUPPORTED");addEventLog("CAMERA ERROR");return}try{setText(ui.cameraState,"STARTING CAMERA...");cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});ui.driverCamera.srcObject=cameraStream;await ui.driverCamera.play();if(!setupFaceMesh()){stopCamera();return}cameraRunning=true;setText(ui.cameraState,"CAMERA ACTIVE");ui.cameraBtn.textContent="STOP CAMERA";addEventLog("CAMERA STARTED");runFaceDetection()}catch(error){console.error("Camera error:",error);setText(ui.cameraState,"CAMERA ERROR");addEventLog("CAMERA ERROR")}}
function stopCamera(){const wasRunning=cameraRunning;cameraRunning=false;if(cameraFrameTimer){clearTimeout(cameraFrameTimer);cameraFrameTimer=null}if(cameraStream)cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;ui.driverCamera.srcObject=null;faceMesh=null;eyesClosedSince=0;eyeOpenBaseline=.30;smoothedEAR=null;if(drowsyPhase!=="NORMAL")sendCmd("EYE:CLEAR");drowsyPhase="NORMAL";clearDrowsyUI();setText(ui.eyeState,"EYES: --");setText(ui.cameraState,"CAMERA OFF");ui.cameraBtn.textContent="START CAMERA";if(wasRunning)addEventLog("CAMERA STOPPED")}
function bindHold(button,onStart,onEnd){button.addEventListener("pointerdown",event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);onStart()});["pointerup","pointercancel","lostpointercapture"].forEach(type=>button.addEventListener(type,onEnd))}
ui.connectBtn.addEventListener("click",connectBLE);ui.gearFwdBtn.addEventListener("click",()=>setGear("forward"));ui.gearRevBtn.addEventListener("click",()=>setGear("reverse"));ui.stopBtn.addEventListener("pointerdown",event=>{event.preventDefault();stopMotion(true)});ui.stopBtn.addEventListener("click",event=>{if(event.detail===0)stopMotion(true)});ui.ecoBtn.addEventListener("click",()=>setMode("ECO"));ui.sportBtn.addEventListener("click",()=>setMode("SPORT"));ui.parkingBtn.addEventListener("click",()=>setParkingMode(!parkingMode));ui.gpsReqBtn.addEventListener("click",()=>sendCmd("GPS?"));ui.msgSendBtn.addEventListener("click",async()=>{const message=ui.msgInput.value.trim();if(!message){setText(ui.msgStatus,"ENTER A MESSAGE");return}setText(ui.msgStatus,"SENDING...");if(await sendCmd(`MSG:${message}`)){ui.msgInput.value="";smsState="SENT";addEventLog("SMS SENT");setText(ui.msgStatus,"MESSAGE SENT")}else{smsState="FAILED";addEventLog("SMS FAILED");setText(ui.msgStatus,"CAR NOT CONNECTED")}updateConnectionScreen();if(activePanel)openPanelContent(activePanel)});ui.cameraBtn.addEventListener("click",()=>cameraRunning?stopCamera():startCamera());bindHold(ui.moveBtn,()=>startMotion(currentGear),releaseMotion);bindHold(ui.leftBtn,()=>setSteering(-MAX_STEERING),()=>releaseSteering(-MAX_STEERING));bindHold(ui.rightBtn,()=>setSteering(MAX_STEERING),()=>releaseSteering(MAX_STEERING));$("menuOpenBtn").addEventListener("click",openMenu);$("menuCloseBtn").addEventListener("click",closeMenu);$("drawerBackdrop").addEventListener("click",closeMenu);document.querySelectorAll("[data-panel]").forEach(button=>button.addEventListener("click",()=>openPanel(button.dataset.panel)));$("panelCloseBtn").addEventListener("click",closePanel);$("panelOverlay").addEventListener("click",event=>{if(event.target===$("panelOverlay"))closePanel()});document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeMenu();closePanel()}});requestAnimationFrame(animateGauges);window.addEventListener("blur",()=>stopMotion(true));document.addEventListener("visibilitychange",()=>{if(document.hidden)stopMotion(true)});updateSpeed(0);updateDriveReadout();updateConnectionScreen();
